[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# CORRECTION CRITIQUE : Redirects pour SPA React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyAbHhGjL9KYlURcBauxjh9FXTxjnO_KYDE"
  VITE_FIREBASE_AUTH_DOMAIN = "centraldocs-616b8.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "centraldocs-616b8"
  VITE_FIREBASE_STORAGE_BUCKET = "centraldocs-616b8.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "838208017668"
  VITE_FIREBASE_APP_ID = "1:838208017668:web:1a5837c138b50592feec51"
  VITE_FIREBASE_MEASUREMENT_ID = "G-LZ53BYV2LW"